apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: azure-test-repo
  annotations:
    github.com/project-slug: sandip444/ecommerce
spec:
  type: openapi
  lifecycle: production
  owner: sandip
  definition:
    $json: https://github.com/sandip444/ecommerce/catalog-info.json
